// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynuhmfsllswgghlicpjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludWhtZnNsbHN3Z2dobGljcGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjI1MDgsImV4cCI6MjA2NjMzODUwOH0.8MVQPWajuxHqEg0M-a3-bYzpMjDLwi7f7Vbz9cEl9ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);